import {GenFields, CompanyResults, Company} from '@apiCaller';

export const fragmentGetAllCompany: GenFields<CompanyResults> = [
  'totalCount',
  {
    results: [
      '_id',
      'applied',
      'careerName',
      'code',
      'contactName',
      'createdAt',
      'defaultRecord',
      'description',
      'hasEvaluated',
      'highlight',
      'isHot',
      'isIdentified',
      'isIdentified',
      'isTop',
      'keywords',
      'location',
      'name',
      'phoneNumber',
      'point',
      'size',
      'slug',
      'status',
      'subscribe',
      'updatedAt',
      'videos',
      'view',
      {
        benefits: [
          '_id',
          'content',
          {icon: ['_id', {icon: ['default', 'medium', 'small']}]},
        ],
      },
      {
        career: [
          '_id',
          'createdAt',
          'description',
          'keywords',
          'name',
          'slug',
          'updatedAt',
        ],
      },
      {images: ['default', 'medium', 'small']},
      {logo: ['default', 'medium', 'small']},
      {province: ['_id', 'code', 'name']},
      {user: ['_id', 'username', 'title']},
    ],
  },
];

export const fragmentGetCompanyById: GenFields<Company> = [
  '_id',
  'applied',
  'careerName',
  'code',
  'contactName',
  'createdAt',
  'defaultRecord',
  'description',
  'hasEvaluated',
  'careerName',
  'highlight',
  'isHot',
  'isIdentified',
  'isIdentified',
  'isTop',
  'keywords',
  'location',
  'name',
  'phoneNumber',
  'point',
  'size',
  'slug',
  'status',
  'subscribe',
  'updatedAt',
  'videos',
  'view',
  {
    benefits: [
      '_id',
      'content',
      {
        icon: [
          '_id',
          'description',
          'name',
          {icon: ['default', 'medium', 'small']},
        ],
      },
    ],
  },
  {
    career: [
      '_id',
      'createdAt',
      'description',
      'keywords',
      'name',
      'slug',
      'updatedAt',
    ],
  },
  {images: ['default', 'medium', 'small']},
  {logo: ['default', 'medium', 'small']},
  {province: ['_id', 'code', 'name']},
  {user: ['_id', 'username', 'title']},
];
