import {GenFields, Notify, InvitationApply} from '@apiCaller';

export const fragmentGetNotifyByUserId: GenFields<Notify[]> = [
  '_id',
  'createdAt',
  'description',
  'keywords',
  'name',
  'noticeExpiration',
  'createdAt',
  'recruitmentId',
  'seen',
  'slug',
  'updatedAt',
  {company: ['_id', 'name', 'applied', 'location']},
  'recruitmentId',
  {
    scheduleInterview: [
      '_id',
      'positionInterview',
      'scheduleType',
      'scheduleTime',
      'scheduleLocation',
      'interviewerName',
      'interviewerPhone',
      'isConfirmFromReceiver',
      'status',
      'interviewerEmail',
      {company: ['location']},
      {recruitment: ['_id']},
    ],
  },
  {
    invitationApply: [
      '_id',
      'address',
      'createdAt',
      'senderEmail',
      'senderPhone',
      'positionApply',
      'senderEmail',
      'isConfirmFromReceiver',
      'positionApply',
      'senderName',
      'senderPhone',
      'status',
      'updatedAt',
      {company: ['location']},
      {recruitment: ['_id']},
    ],
  },
];

export const fragmentGetNotifyById: GenFields<Notify> = [
  '_id',
  'createdAt',
  'description',
  'keywords',
  'name',
  'noticeExpiration',
  'createdAt',
  'recruitmentId',
  'seen',
  'recruitmentId',
  'slug',
  'updatedAt',
  {company: ['_id', 'name', 'applied', 'location']},
  {
    scheduleInterview: [
      '_id',
      'positionInterview',
      'scheduleType',
      'scheduleTime',
      'isConfirmFromReceiver',
      'scheduleLocation',
      'interviewerName',
      'interviewerPhone',
      'interviewerEmail',
      'status',
      {company: ['location']},
      {recruitment: ['_id']},
    ],
  },
  {
    invitationApply: [
      '_id',
      'address',
      'createdAt',
      'senderEmail',
      'senderPhone',
      'positionApply',
      'senderEmail',
      'positionApply',
      'isConfirmFromReceiver',
      'senderName',
      'senderPhone',
      'status',
      'updatedAt',
      {company: ['location']},
      {recruitment: ['_id']},
    ],
  },
];

export const fragmentGetInvitationById: GenFields<InvitationApply> = [
  '_id',
  'address',
  'createdAt',
  'createdAt',
  'isConfirmFromReceiver',
  'positionApply',
  'senderEmail',
  'senderName',
  'senderPhone',
  'status',
  'updatedAt',
  {company: ['_id', 'name']},
];
