import {GenFields, User} from '@apiCaller';

export const fragmentRefreshProfile: GenFields<User> = [
  '_id',
  'displayName',
  'phoneNumber',
  'email',
  'title',
  'username',
  'code',
  'point',
  'gender',
  {ward: ['name']},
  {district: ['name']},
  {province: ['name', '_id']},
  {street: ['name']},
  {urlAvt: ['default', 'medium', 'small']},
  {
    subscribedCompany: [
      '_id',
      'applied',
      'careerName',
      'code',
      'contactName',
      'createdAt',
      'defaultRecord',
      'description',
      'hasEvaluated',
      'highlight',
      'isHot',
      'isIdentified',
      'isIdentified',
      'isTop',
      'keywords',
      'location',
      'name',
      'phoneNumber',
      'point',
      'size',
      'slug',
      'status',
      'subscribe',
      'updatedAt',
      'videos',
      'view',
      {
        benefits: [
          '_id',
          'content',
          {icon: ['_id', {icon: ['default', 'medium', 'small']}]},
        ],
      },
      {
        career: [
          '_id',
          'createdAt',
          'description',
          'keywords',
          'name',
          'slug',
          'updatedAt',
        ],
      },
      {images: ['default', 'medium', 'small']},
      {logo: ['default', 'medium', 'small']},
      {province: ['_id', 'code', 'name']},
      {user: ['_id', 'username', 'title']},
    ],
  },
  {
    appliedRecruitment: [
      'date',
      {
        recruitment: [
          '_id',
          'companyDescription',
          'companyLocation',
          'companyName',
          'companySize',
          'companySlug',
          'companyVideo',
          'createdAt',
          'dealSalary',
          'name',
          'description',
          'expiredDate',
          'highlight',
          'salaryMax',
          'salaryMin',
          {
            company: ['location', {images: ['default', 'medium', 'small']}],
          },
          'view',
          'createdAt',
          'expiredDate',
          {
            location: ['_id', 'location', 'name', 'updatedAt', 'createdAt'],
          },
          {
            companyImages: ['default', 'medium', 'small'],
          },
        ],
      },
    ],
  },
  {
    savedRecruitment: [
      '_id',
      'companyDescription',
      'companyLocation',
      'companyName',
      'companySize',
      'companySlug',
      'companyVideo',
      'createdAt',
      'dealSalary',
      'name',
      'description',
      'expiredDate',
      'highlight',
      'salaryMax',
      'salaryMin',
      'view',
      'createdAt',
      {company: ['location', {images: ['default', 'medium', 'small']}]},
      'expiredDate',
      {
        location: ['_id', 'location', 'name', 'updatedAt', 'createdAt'],
      },
      {
        companyImages: ['default', 'medium', 'small'],
      },
    ],
  },
];
